# Generated by Django 4.2.2 on 2023-07-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('apellido_cliente', models.CharField(max_length=30)),
                ('telefono_cliente', models.CharField(max_length=30)),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.cuenta')),
            ],
        ),
    ]
